### ISSUE TITLE
Does this compile?

### ISSUE THREAD

**Issue by modulexcite** [savaged/SixNations#3]
Hi,

Is this project still a WIP as it seems like it's missing a few pieces as I'm unable to compile in VS 2017?

**Comment by savaged** [comment]
Hi,
Yes, it is very much WIP. However, I believe it should compile with a "Restore NuGet packages" command.

**Comment by modulexcite** [comment]
Understood, guess I was too eager. :)
I did restore the packages but couldn't compile it because of the following issues:
- missing `Services\AuthTokenService.partial.cs` file.
- `ClientSecret` doesn't exist in `AuthTokenService.cs` file.

**Comment by savaged** [comment]
Oh! Forgot about that, sorry. I'll add a note to the README.

One must add a file in `Services` named `AuthTokenService.partial.cs` with the following contents:

```using System;

namespace SixNations.Desktop.Services
{
    partial class AuthTokenService
    {
        private const string ClientSecret = "your token here";
    }
}
```

Don't forget to add it to your .gitignore file, otherwise the world will know your secret!

**Comment by modulexcite** [comment]
Thank you, much appreciated.
